name: Build

on:
  push:
    branches:
      - main


jobs:
  build-analyze-scan:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clone should be disabled for a better relevancy of analysis.
      - name: Build and analyze with SonarQube    
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Trivy File Scan
        run: trivy fs . > trivyfs.txt

      - name: Docker Build and Push
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
             image: ashfaque9x/swiggy-app
             registry: docker.io
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Trivy Image Scan
        run: trivy image ashfaque9x/swiggy-app > trivyimage.txt


     
  Deploy:
   needs: build-analyze-scan
   runs-on: [self-hosted]
   steps:
     - name: Update kubeconfig
       run: aws eks --region ap-south-1 update-kubeconfig --name virtualtechbox-cluster

     - name: Deploy to Kubernetes
       run: kubectl apply -f deployment-and-service.yml

     - name: Send a Slack Notification
       if: always()
       uses: act10ns/slack@v1
       with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#github-action'
       env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  
